  # (fonts section moved below under flutter:)
name: cognisync_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.0
  cupertino_icons: ^1.0.8
  logging: ^1.2.0

  lottie: ^3.1.0
  just_audio: ^0.9.36
  rxdart: ^0.27.7
  video_player: ^2.8.6
  image_picker: ^1.2.0
  firebase_storage: ^11.7.7
  image: ^4.5.4
  http: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/animations/journal.json
    - assets/animations/medi.json
    - assets/Audios/Meditation.mp3
    - assets/animations/sleep.json
    - assets/Audios/Sleep.mp3
    - assets/game_image/bowl.png
    - assets/game_image/campfire.png
    - assets/game_image/fish.png
    - assets/game_image/necklace.png
    - assets/game_image/tent.png
    - assets/game_image/volcano.png
    - assets/game_image/woman1.png
    - assets/game_image/woman2.png
    - assets/video/brain-loop3.mp4

  fonts:
    - family: GoodTimingBd
      fonts:
        - asset: assets/fonts/good timing bd.otf

    - family: Zentry
      fonts:
        - asset: assets/fonts/zentry-regular.woff2

    - family: General
      fonts:
        - asset: assets/fonts/general.woff2
